version: '3'
services:
  postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    user: root
    network_mode: host

  persistent-postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    user: root
    network_mode: host
    volumes:
      - ${TGI_POSTGRES_MOUNT:-/tmp/tgi-postgres-mount}:/var/lib/postgresql/data

  processing:
    image: "tondi-graph-inspector-processing:latest"
    depends_on:
      - postgres
    command:
      - "/app/processing"
      - "--connection-string=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?sslmode=disable"
      - "--rpcserver=${TGI_RPCSERVER}"
    network_mode: host
    user: root
    restart: always

  api:
    image: "tondi-graph-inspector-api:latest"
    depends_on:
      - postgres
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGHOST=localhost
      - PGPORT=5432
      - API_PORT=${API_PORT}
    command:
      - "npm"
      - "run"
      - "--prefix"
      - "/app"
      - "start"
    network_mode: host
    user: root
    restart: always

  web:
    image: "tondi-graph-inspector-web:latest"
    depends_on:
      - postgres
    command:
      - "serve"
      - "--listen=${WEB_PORT}"
    network_mode: host
    user: root
    restart: always
